// Local icon barrel.
// We deep-import each Phosphor icon individually instead of pulling the full
// `@phosphor-icons/react` barrel (~6MB), which trips Vite 8's dep optimizer.
// Same component API (weight / size / props) as the main package.
export { ArrowRight } from '@phosphor-icons/react/dist/csr/ArrowRight'
export { ArrowUpRight } from '@phosphor-icons/react/dist/csr/ArrowUpRight'
export { ChatCircleDots } from '@phosphor-icons/react/dist/csr/ChatCircleDots'
export { ChatTeardropText } from '@phosphor-icons/react/dist/csr/ChatTeardropText'
export { Clock } from '@phosphor-icons/react/dist/csr/Clock'
export { Check } from '@phosphor-icons/react/dist/csr/Check'
export { Scissors } from '@phosphor-icons/react/dist/csr/Scissors'
export { CaretDown } from '@phosphor-icons/react/dist/csr/CaretDown'
export { CreditCard } from '@phosphor-icons/react/dist/csr/CreditCard'
export { Phone } from '@phosphor-icons/react/dist/csr/Phone'
export { Heart } from '@phosphor-icons/react/dist/csr/Heart'
export { InstagramLogo } from '@phosphor-icons/react/dist/csr/InstagramLogo'
export { MapPin } from '@phosphor-icons/react/dist/csr/MapPin'
export { PawPrint } from '@phosphor-icons/react/dist/csr/PawPrint'
export { ShieldCheck } from '@phosphor-icons/react/dist/csr/ShieldCheck'
export { Storefront } from '@phosphor-icons/react/dist/csr/Storefront'
export { Truck } from '@phosphor-icons/react/dist/csr/Truck'
export { WhatsappLogo } from '@phosphor-icons/react/dist/csr/WhatsappLogo'
export { ShoppingCartSimple } from '@phosphor-icons/react/dist/csr/ShoppingCartSimple'
export { Plus } from '@phosphor-icons/react/dist/csr/Plus'
export { Minus } from '@phosphor-icons/react/dist/csr/Minus'
export { Trash } from '@phosphor-icons/react/dist/csr/Trash'
export { X } from '@phosphor-icons/react/dist/csr/X'
export { ArrowLeft } from '@phosphor-icons/react/dist/csr/ArrowLeft'
export { Copy } from '@phosphor-icons/react/dist/csr/Copy'
export { Bank } from '@phosphor-icons/react/dist/csr/Bank'
